### ISSUE TITLE
License

### ISSUE THREAD

**Issue by risinek** [1f604/personal-projects#1]
Hello!

I have found some interesting stuff in this repo and did some tweaks for my personal usage, but I would like to fork this repo and share my changes.
Specifically I'm talking about this python script https://github.com/1f604/personal-projects/blob/master/decryption/cribsearch.py that I automated a little bit more - automatically finding the key/message without any manual interaction if the messages contain common ASCII characters (can be easily edited to match ones needs).
But unfortunately you haven't specified any license for this repo, so by this "Issue" I'm asking you for permission to spread your interesting work with some enhancements :) 

Cheers,
risinek

**Comment by 1f604** [comment]
Hello risinek!

Feel free to fork and share your changes (preferably publicly!). All I ask for is that you give credit where credit is due. 

I haven't put much thought into what license my code should be. For this stuff, I think either GPLv3 or BSD license. I'm leaning towards GPLv3 for now. 

Thanks,
1f604
